name: Build documentation

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout v6.2.0
        uses: actions/checkout@v2
        with:
          repository: ng-bootstrap/ng-bootstrap
      - run: git fetch --all --tags
      - run: git checkout tags/6.2.0
