name: Build documentation

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ng-bootstrap/ng-bootstrap
          path: ./src/v6.2.0
      - name: Fetch all tags
        run: git fetch --all --tags
      - name: Checkout v6.2.0
        run: git checkout tags/6.2.0
